apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: keywords
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
    isDefault: true
